installCRDs: true

extraArgs:
  - --issuer-ambient-credentials
  - --dns01-recursive-nameservers=123
  - --dns01-recursive-nameservers-only

ingressShim:
  defaultIssuerName: letsencrypt-prod
  defaultIssuerKind: ClusterIssuer
  defaultIssuerGroup: cert-manager.io